export const locationsResponse = {
  rows: [
    {
      id: 1,
      locationName: 'Kigali',
      country: 'Rwanda',
      description:
        'a landlocked country in the Great Rift Valley of Central Africa',
    },
  ],
};

export const locations = [
  {
    id: 1,
    LocationName: 'Kigali',
    country: 'Rwanda',
    description:
      'a landlocked country in the Great Rift Valley of Central Africa',
  },
];

export const allTripRequests = [
  {
    id: 61,
    userId: 10,
    managerId: 3,
    departLocation: 5,
    destinations: ['{"accomodationId":6,"destinationId":1}'],
    tripReason: 'hh',
    departDate: '2022-06-01T00:00:00.000Z',
    returnDate: '2022-06-24T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'RWC-011235',
    address: 'Kigali',
    names: 'bosco',
    gender: 'Female',
    role: 'requester',
    status: 'pending',
    tripType: 'single-city',
    createdAt: '2022-05-19T19:37:17.659Z',
    updatedAt: '2022-05-19T19:37:17.659Z',
    User: {
      id: 10,
      names: 'bosco',
      email: 'senderone@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 51,
    userId: 2,
    managerId: 3,
    departLocation: 1,
    destinations: [
      '{"accommodationId":3,"destinationId":2}',
      '{"accommodationId":1,"destinationId":4}',
      '{"accommodationId":4,"destinationId":3}',
    ],
    tripReason: 'Expanding my Horizons',
    departDate: '2022-10-29T00:00:00.000Z',
    returnDate: '2023-09-12T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'ZXC9876',
    address: 'KAMPALA-ENTEBE-KAMINA',
    names: 'James Clovis',
    gender: 'male',
    role: 'requester',
    status: 'pending',
    tripType: 'multicity',
    createdAt: '2022-05-19T15:18:35.875Z',
    updatedAt: '2022-05-19T15:55:51.465Z',
    User: {
      id: 2,
      names: 'seeduser',
      email: 'seeduser@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 50,
    userId: 2,
    managerId: 3,
    departLocation: 1,
    destinations: [
      '{"accommodationId":3,"destinationId":2}',
      '{"accommodationId":1,"destinationId":4}',
      '{"accommodationId":4,"destinationId":3}',
    ],
    tripReason: 'Expanding my Horizons',
    departDate: '2022-10-09T00:00:00.000Z',
    returnDate: '2023-09-12T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'ZXC9876',
    address: 'KAMPALA-ENTEBE-KAMINA',
    names: 'James Clovis',
    gender: 'male',
    role: 'requester',
    status: 'approved',
    tripType: 'multicity',
    createdAt: '2022-05-19T15:18:10.918Z',
    updatedAt: '2022-05-19T16:00:52.776Z',
    User: {
      id: 2,
      names: 'seeduser',
      email: 'seeduser@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 48,
    userId: 2,
    managerId: 3,
    departLocation: 1,
    destinations: [
      '{"accommodationId":3,"destinationId":2}',
      '{"accommodationId":1,"destinationId":3}',
      '{"accommodationId":3,"destinationId":2}',
    ],
    tripReason: 'to get new perspective',
    departDate: '2022-11-08T00:00:00.000Z',
    returnDate: '2023-11-18T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'ZXC9876',
    address: 'KAMPALA-ENTEBE-KAMINA',
    names: 'James Clovis',
    gender: 'male',
    role: 'requester',
    status: 'pending',
    tripType: 'multicity',
    createdAt: '2022-05-19T05:02:46.205Z',
    updatedAt: '2022-05-19T05:05:16.915Z',
    User: {
      id: 2,
      names: 'seeduser',
      email: 'seeduser@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 47,
    userId: 2,
    managerId: 3,
    departLocation: 1,
    destinations: [
      '{"accommodationId":3,"destinationId":2}',
      '{"accommodationId":1,"destinationId":3}',
      '{"accommodationId":3,"destinationId":2}',
    ],
    tripReason: 'to get new perspective',
    departDate: '2022-11-09T00:00:00.000Z',
    returnDate: '2023-11-12T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'ZXC9876',
    address: 'KAMPALA-ENTEBE-KAMINA',
    names: 'James Clovis',
    gender: 'male',
    role: 'requester',
    status: 'approved',
    tripType: 'multicity',
    createdAt: '2022-05-19T05:02:27.999Z',
    updatedAt: '2022-05-19T05:59:55.435Z',
    User: {
      id: 2,
      names: 'seeduser',
      email: 'seeduser@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 44,
    userId: 2,
    managerId: 3,
    departLocation: 2,
    destinations: [
      '{"accommodationId":3,"destinationId":1}',
      '{"accommodationId":1,"destinationId":3}',
      '{"accommodationId":4,"destinationId":2}',
    ],
    tripReason: 'Traveling for vacation',
    departDate: '2022-10-24T00:00:00.000Z',
    returnDate: '2023-09-13T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'ZXC9876',
    address: 'KAMPALA-ENTEBE-KAMINA',
    names: 'James Clovis',
    gender: 'male',
    role: 'requester',
    status: 'pending',
    tripType: 'multicity',
    createdAt: '2022-05-18T05:17:38.312Z',
    updatedAt: '2022-05-19T15:58:06.986Z',
    User: {
      id: 2,
      names: 'seeduser',
      email: 'seeduser@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 41,
    userId: 2,
    managerId: 3,
    departLocation: 2,
    destinations: [
      '{"accommodationId":3,"destinationId":1}',
      '{"accommodationId":1,"destinationId":3}',
      '{"accommodationId":4,"destinationId":2}',
    ],
    tripReason: 'Traveling for vacation',
    departDate: '2022-10-20T00:00:00.000Z',
    returnDate: '2023-09-13T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'ZXC9876',
    address: 'KAMPALA-ENTEBE-KAMINA',
    names: 'James Clovis',
    gender: 'male',
    role: 'requester',
    status: 'rejected',
    tripType: 'multicity',
    createdAt: '2022-05-18T05:15:20.010Z',
    updatedAt: '2022-05-19T15:56:09.917Z',
    User: {
      id: 2,
      names: 'seeduser',
      email: 'seeduser@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 17,
    userId: 2,
    managerId: 3,
    departLocation: 1,
    destinations: [
      '{"accommodationId":3,"destinationId":2}',
      '{"accommodationId":1,"destinationId":1}',
      '{"accommodationId":4,"destinationId":2}',
    ],
    tripReason: 'Relaxing, life is to short',
    departDate: '2022-10-01T00:00:00.000Z',
    returnDate: '2023-09-12T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'ZXC9876',
    address: 'KAMPALA-ENTEBE-KAMINA',
    names: 'James Clovis',
    gender: 'male',
    role: 'requester',
    status: 'approved',
    tripType: 'multicity',
    createdAt: '2022-05-16T22:39:06.242Z',
    updatedAt: '2022-05-16T23:21:59.831Z',
    User: {
      id: 2,
      names: 'seeduser',
      email: 'seeduser@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 11,
    userId: 10,
    managerId: 3,
    departLocation: 1,
    destinations: [
      '{"accommodationId":3,"destinationId":2}',
      '{"accommodationId":1,"destinationId":2}',
    ],
    tripReason: 'Free Tours',
    departDate: '2022-10-09T00:00:00.000Z',
    returnDate: '2023-09-12T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'RWC-011235',
    address: 'Kigali',
    names: 'bosco',
    gender: 'Female',
    role: 'requester',
    status: 'pending',
    tripType: 'multicity',
    createdAt: '2022-05-16T09:46:15.755Z',
    updatedAt: '2022-05-19T16:01:27.674Z',
    User: {
      id: 10,
      names: 'bosco',
      email: 'senderone@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 10,
    userId: 10,
    managerId: 3,
    departLocation: 1,
    destinations: [
      '{"accommodationId":1,"destinationId":2}',
      '{"accommodationId":1,"destinationId":3}',
    ],
    tripReason: 'Free Tours',
    departDate: '2023-11-09T00:00:00.000Z',
    returnDate: '2024-07-12T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'RWC-011235',
    address: 'Kigali',
    names: 'bosco',
    gender: 'Female',
    role: 'requester',
    status: 'pending',
    tripType: 'multicity',
    createdAt: '2022-05-16T09:33:11.838Z',
    updatedAt: '2022-05-17T08:47:08.703Z',
    User: {
      id: 10,
      names: 'bosco',
      email: 'senderone@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 9,
    userId: 10,
    managerId: 3,
    departLocation: 1,
    destinations: [
      '{"accommodationId":1,"destinationId":2}',
      '{"accommodationId":1,"destinationId":3}',
    ],
    tripReason: 'Free Tours',
    departDate: '2022-11-09T00:00:00.000Z',
    returnDate: '2023-07-12T00:00:00.000Z',
    rememberMe: true,
    passportNumber: 'RWC-011235',
    address: 'Kigali',
    names: 'bosco',
    gender: 'Female',
    role: 'requester',
    status: 'pending',
    tripType: 'multicity',
    createdAt: '2022-05-16T09:25:58.087Z',
    updatedAt: '2022-05-17T17:12:52.159Z',
    User: {
      id: 10,
      names: 'bosco',
      email: 'senderone@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 7,
    userId: 13,
    managerId: 3,
    departLocation: 2,
    destinations: [
      '{"accommodationId":1,"destinationId":1}',
      '{"accommodationId":2,"destinationId":2}',
    ],
    tripReason: 'this is to test ',
    departDate: '2024-04-03T00:00:00.000Z',
    returnDate: '2024-04-05T00:00:00.000Z',
    rememberMe: false,
    passportNumber: 'ZXC9876',
    address: 'KAMPALA-ENTEBE-KAMINA',
    names: 'bosco',
    gender: 'male',
    role: 'requester',
    status: 'pending',
    tripType: null,
    createdAt: '2022-04-21T15:59:05.857Z',
    updatedAt: '2022-05-18T07:42:41.412Z',
    User: {
      id: 13,
      names: 'bosco',
      email: 'senderfour@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
  {
    id: 6,
    userId: 13,
    managerId: 3,
    departLocation: 2,
    destinations: [
      '{"accommodationId":1,"destinationId":1}',
      '{"accommodationId":2,"destinationId":2}',
    ],
    tripReason: 'this is to test ',
    departDate: '2024-04-03T00:00:00.000Z',
    returnDate: '2024-04-05T00:00:00.000Z',
    rememberMe: false,
    passportNumber: 'ZXC9876',
    address: 'KAMPALA-ENTEBE-KAMINA',
    names: 'bosco',
    gender: 'male',
    role: 'requester',
    status: 'pending',
    tripType: null,
    createdAt: '2022-04-21T15:59:05.857Z',
    updatedAt: '2022-04-21T15:59:05.857Z',
    User: {
      id: 13,
      names: 'bosco',
      email: 'senderfour@gmail.com',
      roleId: 5,
      managerId: 3,
      isActive: null,
      verified: true,
      notifyByEmail: true,
    },
  },
];

export const currentUserInfo = {
  names: 'Seed User',
  roleName: 'requester',
  roleId: 5,
  token: 'tokennnnnnnnn',
};
