export const SET_ACCOMMODATIONS = 'SET_ACCOMMODATIONS';
export const SET_LOCATIONS = 'SET_LOCATIONS';
export const SET_TRIP_REQUESTS = 'SET_TRIP_REQUESTS';
export const DELETE_TRIP_REQUEST = 'DELETE_TRIP_REQUEST';
export const APPROVE_TRIP_REQUEST = 'APPROVE_TRIP_REQUEST';
export const REJECT_TRIP_REQUEST = 'REJECT_TRIP_REQUEST';
export const LOAD_TRIP_REQUESTS = 'LOAD_TRIP_REQUESTS';
export const SET_TRIPS_OWNERS = 'SET_TRIPS_OWNERS';
export const ACCOMMODATIONS_ERROR = 'ACCOMMODATIONS_ERROR';
export const CLOSE_SNACKBAR = 'CLOSE_SNACKBAR';
export const OPEN_SNACKBAR = 'OPEN_SNACKBAR';
export const OPEN_GLOBAL_SNACKBAR = 'OPEN_GLOBAL_SNACKBAR';
export const CLOSE_GLOBAL_SNACKBAR = 'CLOSE_GLOBAL_SNACKBAR';

export const OPEN_LOADER = 'OPEN_LOADER';
export const CLOSE_LOADER = 'CLOSE_LOADER';

export const LOGOUT = 'LOGOUT';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SET_CURRENT_USER_PROFILE = 'SET_CURRENT_USER_PROFILE';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIRURE = 'USER_REGISTER_FAIRURE';

// LOGIN ACTION TYPES
export const LoginTypes = {
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',
};
